#!/usr/bin/env bash
# Force-publish an external host port on the panel Postgres container.
# Does NOT rely on compose port merging (which often leaves only 127.0.0.1:5433).
#
#   sudo bash scripts/publish-managed-pg-port.sh
#   sudo bash scripts/publish-managed-pg-port.sh --port 18081
#
set -euo pipefail

ROOT="${BARN_INSTALL_DIR:-${DOCK_PILOT_INSTALL_DIR:-}}"
if [[ -z "$ROOT" ]]; then
  if [[ -f ./.env ]] && { [[ -f ./docker-compose.full.yml ]] || [[ -f ./docker-compose.barn-full.yml ]]; }; then
    ROOT="$(pwd)"
  elif [[ -f /opt/dock-pilot/.env ]]; then
    ROOT="/opt/dock-pilot"
  else
    ROOT="/opt/barn"
  fi
fi
cd "$ROOT"

EXTRA_PORT="18081"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) EXTRA_PORT="${2:-}"; shift 2 ;;
    --port=*) EXTRA_PORT="${1#*=}"; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

log() { echo "[barn-publish-pg] $*" >&2; }
die() { echo "[barn-publish-pg] ERROR: $*" >&2; exit 1; }

[[ "$EXTRA_PORT" =~ ^[0-9]+$ ]] || die "invalid --port"
[[ -f .env ]] || die "no .env in $ROOT"
set -a
# shellcheck disable=SC1091
source ./.env
set +a

PG_HOST_PORT="${POSTGRES_HOST_PORT:-5433}"
[[ "$EXTRA_PORT" != "$PG_HOST_PORT" ]] || die "managed port must differ from panel port ${PG_HOST_PORT}"

CTR=""
for c in dock-pilot-postgres barn-postgres dockpilot-postgres; do
  if docker inspect "$c" >/dev/null 2>&1; then
    CTR="$c"
    break
  fi
done
[[ -n "$CTR" ]] || die "no panel postgres container found"

IMG="$(docker inspect "$CTR" --format '{{.Config.Image}}')"
VOL="$(docker inspect "$CTR" --format '{{range .Mounts}}{{if eq .Destination "/var/lib/postgresql/data"}}{{.Name}}{{end}}{{end}}')"
[[ -n "$VOL" ]] || die "could not find PGDATA volume on $CTR"
RESTART="$(docker inspect "$CTR" --format '{{.HostConfig.RestartPolicy.Name}}')"
[[ -n "$RESTART" ]] || RESTART="unless-stopped"

# Preserve env from the running container (user/password/db already baked into PGDATA,
# but POSTGRES_* must stay consistent for tooling).
ENV_ARGS=()
while IFS= read -r line; do
  [[ -n "$line" ]] || continue
  case "$line" in
    POSTGRES_*|PGDATA=*) ENV_ARGS+=(-e "$line") ;;
  esac
done < <(docker inspect "$CTR" --format '{{range .Config.Env}}{{println .}}{{end}}')

log "Container: $CTR"
log "Image:     $IMG"
log "Volume:    $VOL"
log "Ports:     127.0.0.1:${PG_HOST_PORT}->5432  and  0.0.0.0:${EXTRA_PORT}->5432"

# Persist for future compose ups (explicit !override so merge cannot drop 18081).
COMPOSE="docker-compose.full.yml"
COMPOSE_P=""
if docker inspect dock-pilot-postgres >/dev/null 2>&1 || [[ "$CTR" == dock-pilot-postgres ]]; then
  [[ -f "$COMPOSE" ]] || COMPOSE="docker-compose.dock-pilot.yml"
  COMPOSE_P="dock-pilot"
  PG_COMPOSE_VOL="dock_pilot_pg"
else
  COMPOSE="docker-compose.barn-full.yml"
  [[ -f "$COMPOSE" ]] || COMPOSE="docker-compose.barn.yml"
  [[ -f "$COMPOSE" ]] || COMPOSE="docker-compose.full.yml"
  PG_COMPOSE_VOL="barn_pg"
fi
OVERRIDE="${ROOT}/docker-compose.barn-pgdata.yml"
cat >"$OVERRIDE" <<EOF
# Generated by publish-managed-pg-port.sh — replace ports entirely (!override)
services:
  postgres:
    ports: !override
      - "127.0.0.1:${PG_HOST_PORT}:5432"
      - "0.0.0.0:${EXTRA_PORT}:5432"
volumes:
  ${PG_COMPOSE_VOL}:
    external: true
    name: ${VOL}
EOF
log "Wrote $OVERRIDE"

log "Recreating ${CTR} with docker run (bypasses compose merge)..."
docker stop --time 30 "$CTR" >/dev/null
docker rm -f "$CTR" >/dev/null

run_cmd=(docker run -d
  --name "$CTR"
  --restart "$RESTART"
  -p "127.0.0.1:${PG_HOST_PORT}:5432"
  -p "0.0.0.0:${EXTRA_PORT}:5432"
  -v "${VOL}:/var/lib/postgresql/data")
if ((${#ENV_ARGS[@]} > 0)); then
  run_cmd+=("${ENV_ARGS[@]}")
fi
run_cmd+=("$IMG")
"${run_cmd[@]}" >/dev/null

log "Waiting for postgres..."
ok=0
for _ in $(seq 1 45); do
  if docker exec "$CTR" pg_isready >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 1
done
[[ "$ok" -eq 1 ]] || die "postgres did not become ready"

log "Published ports:"
docker port "$CTR"

# Keep api wired if it was using compose; recreate is optional.
if [[ -f "$COMPOSE" ]]; then
  args=()
  [[ -n "$COMPOSE_P" ]] && args+=(-p "$COMPOSE_P")
  args+=(-f "$COMPOSE" -f "$OVERRIDE")
  log "Refreshing api via compose (override kept for next upgrade)..."
  docker compose "${args[@]}" up -d api 2>/dev/null || true
fi

log "Done. External managed DB: 0.0.0.0:${EXTRA_PORT}"
