// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BackupOperation struct {
	ID           uuid.UUID          `json:"id"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	DatabaseName string             `json:"database_name"`
	InstanceID   pgtype.UUID        `json:"instance_id"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	S3Key        string             `json:"s3_key"`
	SizeBytes    int64              `json:"size_bytes"`
	Message      string             `json:"message"`
	StartedAt    time.Time          `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type BillingAccount struct {
	ID                  uuid.UUID          `json:"id"`
	Provider            string             `json:"provider"`
	ServerIp            string             `json:"server_ip"`
	Login               string             `json:"login"`
	EncryptedPassword   []byte             `json:"encrypted_password"`
	BillmgrUrl          string             `json:"billmgr_url"`
	AlertDays           int32              `json:"alert_days"`
	Enabled             bool               `json:"enabled"`
	CachedExpireDate    pgtype.Date        `json:"cached_expire_date"`
	CachedStatus        string             `json:"cached_status"`
	CachedName          string             `json:"cached_name"`
	CachedCost          string             `json:"cached_cost"`
	LastCheckedAt       pgtype.Timestamptz `json:"last_checked_at"`
	LastCheckError      string             `json:"last_check_error"`
	LastAlertExpireDate pgtype.Date        `json:"last_alert_expire_date"`
	LastAlertAt         pgtype.Timestamptz `json:"last_alert_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type Deployment struct {
	ID         uuid.UUID          `json:"id"`
	SiteID     uuid.UUID          `json:"site_id"`
	Status     string             `json:"status"`
	Message    string             `json:"message"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID uuid.UUID `json:"deployment_id"`
	Level        string    `json:"level"`
	Message      string    `json:"message"`
	CreatedAt    time.Time `json:"created_at"`
}

type NotificationSetting struct {
	ID                        int32              `json:"id"`
	PanelName                 string             `json:"panel_name"`
	Enabled                   bool               `json:"enabled"`
	TelegramChatID            string             `json:"telegram_chat_id"`
	TelegramHttpProxy         string             `json:"telegram_http_proxy"`
	DailyDigestMode           string             `json:"daily_digest_mode"`
	DailyDigestEnabled        bool               `json:"daily_digest_enabled"`
	DailyDigestHour           int32              `json:"daily_digest_hour"`
	DailyDigestMinute         int32              `json:"daily_digest_minute"`
	DailyDigestTimezone       string             `json:"daily_digest_timezone"`
	AlertOnIncidentEnabled    bool               `json:"alert_on_incident_enabled"`
	EncryptedTelegramBotToken []byte             `json:"encrypted_telegram_bot_token"`
	LastDailySentAt           pgtype.Timestamptz `json:"last_daily_sent_at"`
	LastOverallBySite         []byte             `json:"last_overall_by_site"`
	UpdatedAt                 time.Time          `json:"updated_at"`
}

type PanelBackupSetting struct {
	ID                   int32              `json:"id"`
	Enabled              bool               `json:"enabled"`
	Hour                 int32              `json:"hour"`
	Minute               int32              `json:"minute"`
	Timezone             string             `json:"timezone"`
	S3Endpoint           string             `json:"s3_endpoint"`
	S3Region             string             `json:"s3_region"`
	S3Bucket             string             `json:"s3_bucket"`
	S3Prefix             string             `json:"s3_prefix"`
	EncryptedS3AccessKey []byte             `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte             `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     bool               `json:"s3_force_path_style"`
	RetentionCount       int32              `json:"retention_count"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastStatus           string             `json:"last_status"`
	LastError            string             `json:"last_error"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PdbBackupSchedule struct {
	ID                   uuid.UUID          `json:"id"`
	InstanceID           uuid.UUID          `json:"instance_id"`
	DatabaseID           pgtype.UUID        `json:"database_id"`
	Enabled              bool               `json:"enabled"`
	Hour                 int32              `json:"hour"`
	Minute               int32              `json:"minute"`
	Timezone             string             `json:"timezone"`
	S3Endpoint           string             `json:"s3_endpoint"`
	S3Region             string             `json:"s3_region"`
	S3Bucket             string             `json:"s3_bucket"`
	S3Prefix             string             `json:"s3_prefix"`
	EncryptedS3AccessKey []byte             `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte             `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     bool               `json:"s3_force_path_style"`
	UsePanelS3           bool               `json:"use_panel_s3"`
	RetentionCount       int32              `json:"retention_count"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastStatus           string             `json:"last_status"`
	LastError            string             `json:"last_error"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PdbDatabase struct {
	ID         uuid.UUID `json:"id"`
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
	OwnerRole  string    `json:"owner_role"`
	CreatedAt  time.Time `json:"created_at"`
}

type PdbDatabaseActivity struct {
	InstanceID   uuid.UUID          `json:"instance_id"`
	DatabaseName string             `json:"database_name"`
	Inserts      int64              `json:"inserts"`
	Updates      int64              `json:"updates"`
	Deletes      int64              `json:"deletes"`
	LastDmlAt    pgtype.Timestamptz `json:"last_dml_at"`
	CheckedAt    time.Time          `json:"checked_at"`
}

type PdbInstance struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   string      `json:"name"`
	Slug                   string      `json:"slug"`
	Image                  string      `json:"image"`
	ContainerPort          int32       `json:"container_port"`
	HostPort               pgtype.Int4 `json:"host_port"`
	DockerNetworkHost      bool        `json:"docker_network_host"`
	AdminUser              string      `json:"admin_user"`
	EncryptedAdminPassword []byte      `json:"encrypted_admin_password"`
	Status                 string      `json:"status"`
	Message                string      `json:"message"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedAt              time.Time   `json:"updated_at"`
}

type PdbRole struct {
	ID                uuid.UUID `json:"id"`
	InstanceID        uuid.UUID `json:"instance_id"`
	Name              string    `json:"name"`
	EncryptedPassword []byte    `json:"encrypted_password"`
	CreatedAt         time.Time `json:"created_at"`
}

type PdbRoleGrant struct {
	ID         uuid.UUID `json:"id"`
	RoleID     uuid.UUID `json:"role_id"`
	DatabaseID uuid.UUID `json:"database_id"`
	IsOwner    bool      `json:"is_owner"`
}

type ServersEvent struct {
	ID           uuid.UUID   `json:"id"`
	EventID      uuid.UUID   `json:"event_id"`
	NodeID       pgtype.UUID `json:"node_id"`
	NodeUid      pgtype.UUID `json:"node_uid"`
	EventType    string      `json:"event_type"`
	Severity     string      `json:"severity"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	Title        string      `json:"title"`
	Message      string      `json:"message"`
	Payload      []byte      `json:"payload"`
	OccurredAt   time.Time   `json:"occurred_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type ServersIncident struct {
	ID           uuid.UUID          `json:"id"`
	NodeID       pgtype.UUID        `json:"node_id"`
	DedupKey     string             `json:"dedup_key"`
	EventType    string             `json:"event_type"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	Count        int32              `json:"count"`
	FirstSeenAt  time.Time          `json:"first_seen_at"`
	LastSeenAt   time.Time          `json:"last_seen_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	LastEventID  pgtype.UUID        `json:"last_event_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type ServersInstallation struct {
	ID              uuid.UUID          `json:"id"`
	NodeID          pgtype.UUID        `json:"node_id"`
	Host            string             `json:"host"`
	Port            int32              `json:"port"`
	Username        string             `json:"username"`
	Status          string             `json:"status"`
	CurrentStep     string             `json:"current_step"`
	SshFingerprint  string             `json:"ssh_fingerprint"`
	ExpectedNodeUid uuid.UUID          `json:"expected_node_uid"`
	ErrorCode       string             `json:"error_code"`
	ErrorMessage    string             `json:"error_message"`
	InstallKind     string             `json:"install_kind"`
	PanelUrl        string             `json:"panel_url"`
	CertEmail       string             `json:"cert_email"`
	DisplayName     string             `json:"display_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type ServersInstallationLog struct {
	ID             int64     `json:"id"`
	InstallationID uuid.UUID `json:"installation_id"`
	Level          string    `json:"level"`
	Message        string    `json:"message"`
	CreatedAt      time.Time `json:"created_at"`
}

type ServersKnownHost struct {
	ID          uuid.UUID `json:"id"`
	Host        string    `json:"host"`
	Port        int32     `json:"port"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ServersMonitoredService struct {
	ID        uuid.UUID `json:"id"`
	NodeID    uuid.UUID `json:"node_id"`
	UnitName  string    `json:"unit_name"`
	CreatedAt time.Time `json:"created_at"`
}

type ServersNode struct {
	ID              uuid.UUID          `json:"id"`
	NodeUid         uuid.UUID          `json:"node_uid"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	ConnectionType  string             `json:"connection_type"`
	BaseUrl         string             `json:"base_url"`
	Status          string             `json:"status"`
	Capabilities    []byte             `json:"capabilities"`
	Version         string             `json:"version"`
	AgentVersion    string             `json:"agent_version"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	LastPollAt      pgtype.Timestamptz `json:"last_poll_at"`
	PairedAt        pgtype.Timestamptz `json:"paired_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ServersNodeBilling struct {
	ID                uuid.UUID   `json:"id"`
	NodeID            uuid.UUID   `json:"node_id"`
	BillingAccountID  pgtype.UUID `json:"billing_account_id"`
	Mode              string      `json:"mode"`
	ProviderName      string      `json:"provider_name"`
	ProviderUrl       string      `json:"provider_url"`
	ExternalServiceID string      `json:"external_service_id"`
	CostMinor         int64       `json:"cost_minor"`
	Currency          string      `json:"currency"`
	Period            string      `json:"period"`
	NextDueDate       pgtype.Date `json:"next_due_date"`
	AutoRenew         bool        `json:"auto_renew"`
	AlertDays         int32       `json:"alert_days"`
	Comment           string      `json:"comment"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type ServersNodeCredential struct {
	ID             uuid.UUID          `json:"id"`
	NodeID         uuid.UUID          `json:"node_id"`
	Direction      string             `json:"direction"`
	Purpose        string             `json:"purpose"`
	Scopes         []string           `json:"scopes"`
	TokenHash      []byte             `json:"token_hash"`
	EncryptedToken []byte             `json:"encrypted_token"`
	CreatedAt      time.Time          `json:"created_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type ServersOutbox struct {
	ID            int64              `json:"id"`
	EventID       uuid.UUID          `json:"event_id"`
	Payload       []byte             `json:"payload"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     time.Time          `json:"created_at"`
}

type ServersPairingCode struct {
	ID        uuid.UUID          `json:"id"`
	CodeHash  []byte             `json:"code_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type ServersRegistrationToken struct {
	ID              uuid.UUID          `json:"id"`
	InstallationID  pgtype.UUID        `json:"installation_id"`
	ExpectedNodeUid uuid.UUID          `json:"expected_node_uid"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       time.Time          `json:"expires_at"`
	UsedAt          pgtype.Timestamptz `json:"used_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type ServersSetting struct {
	ID                   int32     `json:"id"`
	Mode                 string    `json:"mode"`
	NodeUid              uuid.UUID `json:"node_uid"`
	NodeName             string    `json:"node_name"`
	PublicUrl            string    `json:"public_url"`
	MasterUrl            string    `json:"master_url"`
	NotificationMode     string    `json:"notification_mode"`
	EncryptedMasterToken []byte    `json:"encrypted_master_token"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type ServersSnapshot struct {
	ID               int64         `json:"id"`
	NodeID           uuid.UUID     `json:"node_id"`
	CollectedAt      time.Time     `json:"collected_at"`
	CpuPercent       pgtype.Float8 `json:"cpu_percent"`
	MemoryUsedBytes  pgtype.Int8   `json:"memory_used_bytes"`
	MemoryTotalBytes pgtype.Int8   `json:"memory_total_bytes"`
	DiskUsedPercent  pgtype.Float8 `json:"disk_used_percent"`
	UptimeSeconds    pgtype.Int8   `json:"uptime_seconds"`
	AppsTotal        pgtype.Int4   `json:"apps_total"`
	AppsRunning      pgtype.Int4   `json:"apps_running"`
	AppsUnhealthy    pgtype.Int4   `json:"apps_unhealthy"`
	Payload          []byte        `json:"payload"`
}

type Site struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	Slug               string      `json:"slug"`
	PrimaryUrl         string      `json:"primary_url"`
	GitRepoUrl         string      `json:"git_repo_url"`
	GitBranch          string      `json:"git_branch"`
	DockerfilePath     string      `json:"dockerfile_path"`
	BuildContext       string      `json:"build_context"`
	ContainerPort      int32       `json:"container_port"`
	HostPort           pgtype.Int4 `json:"host_port"`
	NginxSslEnabled    bool        `json:"nginx_ssl_enabled"`
	NginxForceHttps    bool        `json:"nginx_force_https"`
	SiteType           string      `json:"site_type"`
	DockerVolumeMounts string      `json:"docker_volume_mounts"`
	DockerNamedVolumes string      `json:"docker_named_volumes"`
	DockerNetworkHost  bool        `json:"docker_network_host"`
	HealthCheckPath    string      `json:"health_check_path"`
	Status             string      `json:"status"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type SiteDomain struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Domain    string    `json:"domain"`
	IsPrimary bool      `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
}

type SiteEnvVar struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SiteSecret struct {
	ID             uuid.UUID `json:"id"`
	SiteID         uuid.UUID `json:"site_id"`
	Key            string    `json:"key"`
	EncryptedValue []byte    `json:"encrypted_value"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
