// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearNotificationToken = `-- name: ClearNotificationToken :exec
UPDATE notification_settings
SET encrypted_telegram_bot_token = NULL, updated_at = now()
WHERE id = 1
`

func (q *Queries) ClearNotificationToken(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearNotificationToken)
	return err
}

const ensureNotificationSettings = `-- name: EnsureNotificationSettings :one
INSERT INTO notification_settings (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET updated_at = notification_settings.updated_at
RETURNING id, panel_name, enabled, telegram_chat_id, telegram_http_proxy, daily_digest_mode, daily_digest_enabled, daily_digest_hour, daily_digest_minute, daily_digest_timezone, alert_on_incident_enabled, encrypted_telegram_bot_token, last_daily_sent_at, last_overall_by_site, updated_at
`

func (q *Queries) EnsureNotificationSettings(ctx context.Context) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, ensureNotificationSettings)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.PanelName,
		&i.Enabled,
		&i.TelegramChatID,
		&i.TelegramHttpProxy,
		&i.DailyDigestMode,
		&i.DailyDigestEnabled,
		&i.DailyDigestHour,
		&i.DailyDigestMinute,
		&i.DailyDigestTimezone,
		&i.AlertOnIncidentEnabled,
		&i.EncryptedTelegramBotToken,
		&i.LastDailySentAt,
		&i.LastOverallBySite,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT id, panel_name, enabled, telegram_chat_id, telegram_http_proxy, daily_digest_mode, daily_digest_enabled, daily_digest_hour, daily_digest_minute, daily_digest_timezone, alert_on_incident_enabled, encrypted_telegram_bot_token, last_daily_sent_at, last_overall_by_site, updated_at FROM notification_settings WHERE id = 1
`

func (q *Queries) GetNotificationSettings(ctx context.Context) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.PanelName,
		&i.Enabled,
		&i.TelegramChatID,
		&i.TelegramHttpProxy,
		&i.DailyDigestMode,
		&i.DailyDigestEnabled,
		&i.DailyDigestHour,
		&i.DailyDigestMinute,
		&i.DailyDigestTimezone,
		&i.AlertOnIncidentEnabled,
		&i.EncryptedTelegramBotToken,
		&i.LastDailySentAt,
		&i.LastOverallBySite,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationLastDailySent = `-- name: UpdateNotificationLastDailySent :exec
UPDATE notification_settings
SET last_daily_sent_at = $1, updated_at = now()
WHERE id = 1
`

func (q *Queries) UpdateNotificationLastDailySent(ctx context.Context, lastDailySentAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateNotificationLastDailySent, lastDailySentAt)
	return err
}

const updateNotificationLastOverall = `-- name: UpdateNotificationLastOverall :exec
UPDATE notification_settings
SET last_overall_by_site = $1, updated_at = now()
WHERE id = 1
`

func (q *Queries) UpdateNotificationLastOverall(ctx context.Context, lastOverallBySite []byte) error {
	_, err := q.db.Exec(ctx, updateNotificationLastOverall, lastOverallBySite)
	return err
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
UPDATE notification_settings SET
    panel_name = $1,
    enabled = $2,
    telegram_chat_id = $3,
    telegram_http_proxy = $4,
    daily_digest_enabled = $5,
    daily_digest_hour = $6,
    daily_digest_minute = $7,
    daily_digest_timezone = $8,
    alert_on_incident_enabled = $9,
    daily_digest_mode = $10,
    updated_at = now()
WHERE id = 1
RETURNING id, panel_name, enabled, telegram_chat_id, telegram_http_proxy, daily_digest_mode, daily_digest_enabled, daily_digest_hour, daily_digest_minute, daily_digest_timezone, alert_on_incident_enabled, encrypted_telegram_bot_token, last_daily_sent_at, last_overall_by_site, updated_at
`

type UpdateNotificationSettingsParams struct {
	PanelName              string `json:"panel_name"`
	Enabled                bool   `json:"enabled"`
	TelegramChatID         string `json:"telegram_chat_id"`
	TelegramHttpProxy      string `json:"telegram_http_proxy"`
	DailyDigestEnabled     bool   `json:"daily_digest_enabled"`
	DailyDigestHour        int32  `json:"daily_digest_hour"`
	DailyDigestMinute      int32  `json:"daily_digest_minute"`
	DailyDigestTimezone    string `json:"daily_digest_timezone"`
	AlertOnIncidentEnabled bool   `json:"alert_on_incident_enabled"`
	DailyDigestMode        string `json:"daily_digest_mode"`
}

func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSettings,
		arg.PanelName,
		arg.Enabled,
		arg.TelegramChatID,
		arg.TelegramHttpProxy,
		arg.DailyDigestEnabled,
		arg.DailyDigestHour,
		arg.DailyDigestMinute,
		arg.DailyDigestTimezone,
		arg.AlertOnIncidentEnabled,
		arg.DailyDigestMode,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.PanelName,
		&i.Enabled,
		&i.TelegramChatID,
		&i.TelegramHttpProxy,
		&i.DailyDigestMode,
		&i.DailyDigestEnabled,
		&i.DailyDigestHour,
		&i.DailyDigestMinute,
		&i.DailyDigestTimezone,
		&i.AlertOnIncidentEnabled,
		&i.EncryptedTelegramBotToken,
		&i.LastDailySentAt,
		&i.LastOverallBySite,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationToken = `-- name: UpdateNotificationToken :exec
UPDATE notification_settings
SET encrypted_telegram_bot_token = $1, updated_at = now()
WHERE id = 1
`

func (q *Queries) UpdateNotificationToken(ctx context.Context, encryptedTelegramBotToken []byte) error {
	_, err := q.db.Exec(ctx, updateNotificationToken, encryptedTelegramBotToken)
	return err
}
